log_format techproducts '$time_iso8601 '
                        '$remote_addr "$request" $status $body_bytes_sent '
                        'rt=$request_time urt=$upstream_response_time '
                        'ua="$http_user_agent" ref="$http_referer" '
                        'xff="$http_x_forwarded_for" '
                        'upstream=$upstream_addr ustatus=$upstream_status';
